### PR TITLE
PTaH 1.1.0 support

### PR DESCRIPTION
**Pull request by komashchenko**
API PTaH 1.1.0 has changed, therefore older versions are no longer supported.

### CODE REVIEW

**Comment by Drmohammad11** [comment]
hi. i check this site https://ptah.zizt.ru/

but i can not find PTaH 1.1.0!!
is new version ??

**Comment by komashchenko** [comment]
> hi. i check this site https://ptah.zizt.ru/
> 
> but i can not find PTaH 1.1.0!!
> is new version ??

She will be soon, you need to make sure that everything is fine with her
https://github.com/komashchenko/PTaH/pull/20

**Comment by Drmohammad11** [comment]
thank you for support PTaH :x

**Comment by komashchenko** [comment]
> thank you for support PTaH :x

can download :)

**Comment by kgns** [comment]
thank you for updating the integration points for me :)

**Pull request merged**
