### PR TITLE
Operation Shattered Web Knives/Skins

### PR DESCRIPTION
**Pull request by Diam0ndz**
Operation Shattered Web Knives/Skins

### CODE REVIEW

**Comment by LubricantJam** [comment]
Works perfectly and tested, cheers.

**Comment by LubricantJam** [comment]
One thing to note, it doesn't create the new structure with an existing database.

**Comment by Diam0ndz** [comment]
Will take a look after school tomorrow

**Comment by Shane1390** [comment]
Please consider using [my databases file](https://github.com/Shane1390/weapons/blob/master/addons/sourcemod/scripting/weapons/database.sp) here. I've fixed a critical query error in your code (missing quotes on line 493 & 499), that will prevent the table from properly generating in the first place and addressed the issue @LubricantJam discussed.

**Comment by kgns** [comment]
I'm sorry but I can't accept this kind of pull requests. Pull requests are for new features, translation updates and/or general bug fixes. When CS:GO gets an update with new weapons/skins, the changes that needs to be done are mechanical thanks to how they were handled before. I will have to check every line of code you changed to see if there is a problem, and I'd rather to them myself in the same amount of time I have to spend checking. Since new weapons/knives require database modification, if you do something wrong there, it might irreversibly null users' databases. That's why I don't recommend ANYONE to use anything other than a release on this repo for these kind of new skin updates.

**Pull request closed without merging**
